In [19]:
# numpy array is much faster than python list and stored in the contiguous memory loc where list
# elements are stored in scattered way
# perform numerical ops adds, subs, muls etc
import numpy as np
import os, sys
# 2D matrix => 2*3 => (2 rows * 3 cols)
a= np.array([[1,2,3],[5,6,7]], dtype = 'int32')
print(a.shape, a.dtype, a.ndim,a.size)

(2, 3) int32 2 6


In [11]:
a.dtype

dtype('int32')

In [24]:
# accessing row element:
a[:,1:]


array([[2, 3],
       [6, 7]], dtype=int32)

In [25]:
# 3D matrix: 2*3*3 => 2 of (3 rows * 3 cols) matrix
b=np.array([[[1,2,3],[4,5,6],[11,13,14]],[[10,13,15],[12,13,14],[56,57,58]]])
b
            

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [11, 13, 14]],

       [[10, 13, 15],
        [12, 13, 14],
        [56, 57, 58]]])

In [27]:
# picking element from matrix b=(3D) , b[0]=2D,b[1]=2D, b[0][1]=1D this is the way how to handle data
b[1,1:,1:2]

array([[13],
       [57]])

In [32]:
b.ndim

3

In [33]:
b[1].ndim

2

In [41]:
z= np.zeros((5,2), dtype='int8')
z

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [47]:
one = np.ones((5,3),dtype='float16')
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [49]:
# any other number
z= np.full((2,3),7)
z

array([[7, 7, 7],
       [7, 7, 7]])

In [52]:
#random number decimal
np.random.rand(4,2,3)

array([[[0.11158217, 0.6302343 , 0.77580361],
        [0.72414088, 0.41978621, 0.25611338]],

       [[0.30630533, 0.30293842, 0.99976664],
        [0.03780325, 0.48983116, 0.38695983]],

       [[0.16782725, 0.54787215, 0.786438  ],
        [0.53621906, 0.20853201, 0.15670541]],

       [[0.59198917, 0.97187256, 0.58056171],
        [0.22053339, 0.85084771, 0.65375793]]])

In [56]:
#random numner integer => 0 and 5 are lower and upper limit
np.random.randint(0,5,size=(3,3))

array([[1, 4, 1],
       [1, 1, 2],
       [2, 1, 3]])

In [58]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# copy
a= np.array([1,2,3])
b= a
b[1] = 99
b

array([ 1, 99,  3])

In [61]:
a

array([ 1, 99,  3])

In [67]:
# need to copy
a= np.array([1,2,3])
b= a.copy()
b

array([1, 2, 3])

In [69]:
# element wise operation
a +2

array([3, 4, 5])

In [71]:
a*3

array([3, 6, 9])

In [73]:
# statistical ops
a= np.array([[12,13,4],[34,43,23]])
a

array([[12, 13,  4],
       [34, 43, 23]])

In [76]:
# axis x=0 col wise x=1 row wise
np.min(a, axis=0)

array([12, 13,  4])

In [77]:
np.min(a, axis=1)

array([ 4, 23])